[project]
name = "mqe-glass-quality-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pillow>=12.2.0",
    "python-pptx>=1.0.2",
    "scikit-learn>=1.8.0",
    "streamlit>=1.57.0",
]
